version: '3.8'

services:
  backend:
    container_name: backend_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env 
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8080:3000"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      # On synchronise le sous-dossier local avec la racine du container
      - ./frontend/site-vue:/app
      - /app/node_modules
    ports:
      - "3001:80"
    restart: always